version: '3'
services:
  kdc:
    hostname: kerberos.mit.edu
    build:
      context: .
      dockerfile: kdc.dockerfile
  client:
    build:
      context: .
      dockerfile: client.dockerfile
  idp:
    build:
      context: .
      dockerfile: idp.Dockerfile
